name: ask_mobile
description: "A.S.K Flutter Mobile Project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get_cli: ^1.8.1
  get: ^4.7.2
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  animate_do: ^4.2.0
  logger: ^2.5.0
  intl: ^0.18.1
  jwt_decoder: ^2.0.1
  carousel_slider: ^5.0.0
  camera: ^0.11.0+2
  dropdown_search: ^6.0.2
  country_code_picker: ^3.3.0
  cached_network_image: ^3.4.1
  pay_with_paystack: ^1.0.14
  share_plus: ^11.0.0
  path_provider: ^2.1.5
  image_picker: ^1.1.2
  http_parser: ^4.0.2
  device_info_plus: ^11.3.0
  flutter_native_splash: ^2.4.4
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

flutter_native_splash:
  color: "#FFFFFF"
  image: "assets/images/logo-start.png"
  android: true
  ios: true
  android_gravity: "center" #"fill"
  ios_content_mode: "scaleAspectFill" #"scaleToFill"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/icons/

  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Black.ttf

    - family: LatoRegular
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf